#obtain an API login_id and transaction_id according to instructions at https://developer.authorize.net/faqs/#gettranskey

# test key
api_login_id: 4ZzFE9Ff9Zqc
api_transaction_key: 3w3PY2h9gJTsa777

# Production key
# api_login_id: 522g3rmMMu
# api_transaction_key: 8WGWNzF3h8863c9f

#obtained md5 hash value by first setting the hash value in https://sandbox.authorize.net/ under the Account tab->MD5 Hash
md5_value: MD5_TEST
